### ISSUE TITLE
Is mbtiles contain street name, and other tags? How to extract mbtiles data?

### ISSUE THREAD

**Issue by joaokho** [osm2vectortiles/osm2vectortiles#448]
Is it possible to extract single vector that contains all information into string? 
So we can know all tags that include on this vector and their values?

**Comment by ImreSamu** [comment]
>Is mbtiles contain street name, and other tags?

you can find the vector tiles meta definitions in the [osm2vectortiles.tm2source/data.yml]( https://github.com/osm2vectortiles/osm2vectortiles/blob/master/osm2vectortiles.tm2source/data.yml )
see : [ -fields ]

for example  `id: road_label`   ( But this will be change !!! )  
```
 - id: road_label
  fields: 
      class: "One of: motorway, motorway_link, 'trunk', 'primary', 'secondary', 'tertiary', 'link', 'street', 'street_limited', 'pedestrian', 'construction', 'track', 'service', 'ferry', 'path', 'golf'"
      len: Number. Approximate length of the road segment in Mercator meters.
      localrank: Number. Used for shield points only. Priority relative to nearby shields. Useful for limiting shield density.
      name: Local name of the road
      name_de: German name of the road
      name_en: English name of the road
      name_es: Spanish name of the road
      name_fr: French name of the road
      name_ru: Russian name of the road
      name_zh: Chinese name of the road
      ref: Route number of the road
      reflen: Number. How many characters long the ref tag is. Useful for shield styling.
      shield: "The shield style to use. One of: default, mx-federal, mx-state, us-highway, us-highway-alternate, us-highway-business, us-highway-duplex, us-interstate, us-interstate-business, us-interstate-duplex, us-interstate-truck, us-state"

```
**Warning :  [The OSM2Vectortiles tile schema will be change] ( https://github.com/osm2vectortiles/osm2vectortiles/milestone/21)**   
So If you want to use in production - please wait!
