### ISSUE TITLE
import data from own data lost some data

### ISSUE THREAD

**Issue by bearnxx** [osm2vectortiles/osm2vectortiles#456]
I have some shp data. in order to import them to postgre db and use the work flow of osm2vectortiles I transfer the shp data into bj_min.pbf which in the Attach files named bj_min.txt(to use it please rename it to .pbf)
[bj_min.txt](https://github.com/osm2vectortiles/osm2vectortiles/files/541634/bj_min.txt)

This data contains 28 features(ways). the correct display of the data like the picture below
![1](https://cloud.githubusercontent.com/assets/21222866/19559192/40bd5374-9701-11e6-858b-f1c8ed0f9d39.png)

But when I import the data with the osm2vectortiles workflow it display like the picture below
![2](https://cloud.githubusercontent.com/assets/21222866/19559248/7b55856a-9701-11e6-9067-9ffaf5376e69.png)

so I checked the database and found there are only 18 features in the osm_road table. what confuse me is the tags of the way which map the ways to osm_road table are the same why lost 10 features. 
Could you try my test data?  which in the attach files? or just tell me how should I check the workflow.
Thank you!

**Comment by lukasmartinelli** [comment]
That must be something in imposm3 mapping - you could change the `mapping.yml` to accept all road tags for starting (https://imposm.org/docs/imposm3/latest/mapping.html):

Something like this..

```
tables:
  highway_linestring:
    type: linestring
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: highway
      key: highway
      type: string
    - key: oneway
      name: oneway
      type: direction
    - key: layer
      name: layer
      type: integer
    - name: z_order
      type: wayzorder
    - key: tunnel
      name: is_tunnel
      type: bool
    - key: bridge
      name: is_bridge
      type: bool
    - key: name
      name: name
      type: string
    - name: name_en
      key: name:en
      type: string
    mapping:
      highway:
      - __any__
```
