### ISSUE TITLE
Standalone export

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#80]
Ensure and test the main `export` docker runs directly - without access to cloud buckets and queues and logging - if the AWS variables are not set by the user...

The cluster rendering should be triggered by setting the variables - but by default it should not be set. Export started without the system variables should render only on a single machine locally.

This is essential for people to play with this project - and render small maps and cities / countries OSM planet extracts.

**Comment by leblowl** [comment]
Works for me following instructions on the README

**Comment by lukasmartinelli** [comment]
Export has been split up into remote and local components.
The python wrapper no longer wraps around the local export (no benefits there).
And the `export-remote` works like before (perhaps `export-worker` would be a better name).

```yaml
export-remote:
  build: ./src/export
  command: ./export-remote.sh
  volumes:
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
  environment:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_REGION: "eu-central-1"
export-local:
  build: ./src/export
  command: ./export-local.sh
  volumes:
   - ./export:/data/export
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
  environment:
    BBOX: "8.4375 46.07323062540838 9.84375 47.040182144806664"
    MIN_ZOOM: "8"
    MAX_ZOOM: "14"
```
